set(HEADER_FILES
	include/PCH.h
	include/Plugin.h
	include/Application/UI.h
	include/Application/ObjectManipulationManager.h
	include/Application/Configuration/ObjectReferenceFilterConfiguration.h
	include/Application/Configuration/InputManagerConfiguration.h
	include/Application/Persistence.h
	include/Lib/logger.h
	include/Lib/SKSEMenuFramework.h
	include/Lib/HookBuilder.h
	include/Lib/Raycast.h
	include/Lib/RayCollector.h
	include/Lib/Misc.h
	include/Lib/File.h
	include/Lib/Regex.h
	include/Lib/InputManager.h
	include/Lib/ObjectReferenceFilter.h
	include/Lib/Json.h
	include/Interface/ObjectManipulationOverhaul.h
	include/Interface/Papyrus.h
)
