set(HEADER_FILES
	include/PCH.h
	include/Plugin.h
	include/Application/UI.h
	include/Application/ObjectManipulationManager.h
	include/Lib/logger.h
	include/Lib/SKSEMenuFramework.h
	include/Lib/HookBuilder.h
	include/Lib/Raycast.h
	include/Lib/RayCollector.h
	include/Lib/Misc.h
)
