set(SOURCE_FILES
	src/plugin.cpp
	src/Application/ObjectManipulationManager.cpp
	src/Application/Configuration/ObjectReferenceFilterConfiguration.cpp
	src/Application/Configuration/InputManagerConfiguration.cpp
	src/Application/Persistence.cpp
	src/Lib/Raycast.cpp
	src/Lib/RayCollector.cpp
	src/Lib/Misc.cpp
	src/Lib/File.cpp
	src/Lib/Regex.cpp
	src/Lib/InputManager.cpp
	src/Lib/ObjectReferenceFilter.cpp
	src/Lib/Json.cpp
	src/Interface/ObjectManipulationOverhaul.cpp
	src/Interface/Papyrus.cpp
)
