set(SOURCE_FILES
	src/plugin.cpp
	src/Application/UI.cpp
	src/Application/ObjectManipulationManager.cpp
	src/Lib/Raycast.cpp
	src/Lib/RayCollector.cpp
	src/Lib/Misc.cpp
	src/Lib/File.cpp
	src/Lib/Regex.cpp
)
